# Generated by Django 5.0.3 on 2024-03-13 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=230)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('director', models.CharField(max_length=53)),
                ('gener', models.CharField(choices=[('HR', 'Horror'), ('TR', 'Thriller'), ('RM', 'Romantic'), ('AN', 'Animation'), ('CM', 'Comedy'), ('FN', 'Fantasy'), ('AC', 'Action/Adventure'), ('HT', 'Historical'), ('DR', 'Drama'), ('MT', 'Mystery'), ('MC', 'Musical'), ('CR', 'Crime')], max_length=20)),
                ('cover', models.ImageField(null=True, upload_to='moviesapp/covers')),
                ('users_likes', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
